#---
#- name: Exercise for setting up a web server in EC2
#  hosts: all
#  user: ubuntu
#  roles:
#    - setup
---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: 18.224.228.29
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup
